### ISSUE TITLE
Results of competition.

### ISSUE THREAD

**Issue by shiddugmail** [strapi-community/website#9]

**Comment by shiddugmail** [comment]
Hello Sir/Madam, 

Let us know Results of competition

Thank you,
Regards,
Shiddu

**Comment by Eventyret** [comment]
Hello @shiddugmail we will be announcing it today :)
It took the judges some time to reach a verdict etc.
We are also in the process of sending out comms etc with the winners so stay tuned 📻 🎤 🎉
